config/routes.rb
Biblio::Application.routes.draw do
  resources :libros

  get "home/index"

 root :to => 'home#index'

end

app/models/libro.rb
class Libro < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @libros }
    end
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
    @libro = Libro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @libro }
    end
  end

  # GET /libros/new
  # GET /libros/new.json
  def new
    @libro = Libro.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @libro }
    end
  end

  # GET /libros/1/edit
  def edit
    @libro = Libro.find(params[:id])
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(params[:libro])

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render json: @libro, status: :created, location: @libro }
      else
        format.html { render action: "new" }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /libros/1
  # PUT /libros/1.json
  def update
    @libro = Libro.find(params[:id])

    respond_to do |format|
      if @libro.update_attributes(params[:libro])
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro = Libro.find(params[:id])
    @libro.destroy

    respond_to do |format|
      format.html { redirect_to libros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%=link_to "Mis Libros", libros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biblio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/libros/_form.html.erb
<%= form_for(@libro) do |f| %>
  <% if @libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% @libro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Titulo %><br />
    <%= f.text_field :Titulo %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :Idioma %><br />
    <%= f.text_field :Idioma %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :Resumen %><br />
    <%= f.text_field :Resumen %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editing libro</h1>

<%= render 'form' %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

app/views/libros/index.html.erb
<h1>Listing libros</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>String</th>
    <th>Idioma</th>
    <th>String</th>
    <th>Resumen</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @libros.each do |libro| %>
  <tr>
    <td><%= libro.Titulo %></td>
    <td><%= libro.string %></td>
    <td><%= libro.Idioma %></td>
    <td><%= libro.string %></td>
    <td><%= libro.Resumen %></td>
    <td><%= libro.text %></td>
    <td><%= link_to 'Show', libro %></td>
    <td><%= link_to 'Edit', edit_libro_path(libro) %></td>
    <td><%= link_to 'Destroy', libro, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Libro', new_libro_path %>

app/views/libros/new.html.erb
<h1>New libro</h1>

<%= render 'form' %>

<%= link_to 'Back', libros_path %>

app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @libro.Titulo %>
</p>

<p>
  <b>String:</b>
  <%= @libro.string %>
</p>

<p>
  <b>Idioma:</b>
  <%= @libro.Idioma %>
</p>

<p>
  <b>String:</b>
  <%= @libro.string %>
</p>

<p>
  <b>Resumen:</b>
  <%= @libro.Resumen %>
</p>

<p>
  <b>Text:</b>
  <%= @libro.text %>
</p>


<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>